# Generated by Django 4.2.2 on 2023-06-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=100)),
                ('member', models.IntegerField()),
            ],
        ),
    ]
