# Generated by Django 4.2.2 on 2023-07-01 14:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.club'),
            preserve_default=False,
        ),
    ]
