# Generated by Django 4.2.2 on 2023-07-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_comment_club'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
